# Generated by Django 5.2.7 on 2025-10-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dataentry_extract_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='extract_at',
            new_name='extracted_at',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='social_reason',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='cnpj_prestador',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='nome_prestador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
