# Generated by Django 5.2.7 on 2025-10-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_extract_at_dataentry_extracted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='email_prestador',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='telefone_prestador',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
